### ISSUE TITLE
14.0 release 

### ISSUE THREAD

**Issue by rygrass** [andreashauschild/openttd-server#13]
Hello, would it be possible to get the latest release?

Thanks
![Screenshot 2024-04-17 220608](https://github.com/andreashauschild/openttd-server/assets/60543137/7d0edcbb-d38d-48cc-abae-3efd8f1accac)

**Comment by andreashauschild** [comment]
Thank you for notifying me about the new OpenTTD version. I have upgraded the OpenTTD server to version 14.0. Enjoy playing!

**Comment by andreashauschild** [comment]
Closed
