### ISSUE TITLE
14.1 Version

### ISSUE THREAD

**Issue by WuGGu** [andreashauschild/openttd-server#14]
Hi Andreas, 

first of all thanks for the great launcher. How can I update to 14.1 as Server version?

All the best 

Martin

**Comment by andreashauschild** [comment]
Hi Martin,
i updated the project to the current version 14.1. You can now pull the newest version.

Kind Regards
Andreas

**Comment by WuGGu** [comment]
WoW thanks so much for the quick push to 14.1 <3
