### ISSUE TITLE
Feature request - Allow admin port setup

### ISSUE THREAD

**Issue by Thebys** [andreashauschild/openttd-server#15]
Hello, once again I am enjoying your OpenTTD server orchestrator. This time I am trying to connect some [monitoring](https://github.com/Thebys/php-openttd-admin) to my games using OpenTTD Admin Port feature. When both `server_admin_port` and `admin_password` are set the game provides extra management [features](https://github.com/OpenTTD/OpenTTD/blob/master/docs/admin_network.md) on the port. There is nothing preventing it from working with your server, but it is a pain to set up, because:
1. Admin port / password are not options in GUI (create server) 

Edit - Good Workaround is having the admin port set up in openttd.cfg and the password in secrets.cfg.

It would be nice to be able to set up admin port and password when creating a server.

Thank you for your work and considering this.

**Comment by andreashauschild** [comment]
Hi Thebys,
i will look into it, as I expect this to be a small change. The implementation details for setting default overwrites for attributes in the OpenTTD configuration files are already in place.

**Comment by andreashauschild** [comment]
Hi,

I released a new version where you can set the server_admin_port and the admin_password in the server creation/edit dialog. I performed some testing, and it worked (though I normally don't use the admin connection). Could you please verify if it works as expected?

Additionally, don't forget to define the admin port in your Docker configuration to make it accessible ;)

**Comment by Thebys** [comment]
Outstanding work! I've updated my stack in Portainer to include dedicated admin ports (I choose 3939-3959) and I confirm it works fine (I've set up two games) and as expected - see remote connection from my app on screenshot. Thank you very much, closing! <3 

![image](https://github.com/user-attachments/assets/331745c2-725d-4323-a9a4-810b27e0cda0)
