### ISSUE TITLE
Can you repack the repo for 13.0 RC1? 

### ISSUE THREAD

**Issue by zazzn** [andreashauschild/openttd-server#3]
I just spent a ton of time (updating the image) I'm not savvy at all with linux/docker. I was able to get it to work, but the website is broken.

Any chance you can release a 13.0 RC1 update?

**Comment by andreashauschild** [comment]
Hi can you please post your Dockerfile, so that i can look into it. If i have some spare time i will look how much effort it will take to provide a container von the RC1.

**Comment by zazzn** [comment]
I was able to get it working; I spun up a new container, uninstalled the version there and installed the new version we good

**Comment by zazzn** [comment]
Any plans to update for the official 13 release?

**Comment by tjerkkamstra** [comment]
Hi! This update would be highly apreciated. Now I must install an older version of OpenTTD to make it work. I love the work you done though: I got it working with a few tweaks.

**Comment by andreashauschild** [comment]
Have missed the 13.0 release i will update openttd server asap.

**Comment by tjerkkamstra** [comment]
Keep in mind that the RC1 is already updated to a main release version. It runs smoothly on windows 11, so hopefully so will the server!

**Comment by andreashauschild** [comment]
I released a new version of openttd-server which runs the game version 13.0
The game files are now located at `/home/openttd/openttd-13`

Have funt to check it out ;)

**Comment by andreashauschild** [comment]
Version 13.0 released

**Comment by tjerkkamstra** [comment]
Hero. Will do tomorrow!

Tried a few other containers but did not really like them. So if this works
we're a bunch of happy gamers.

Met vriendelijke groet,

Tjerk Kamstra

Op za 25 feb. 2023 00:52 schreef andreashauschild ***@***.***
