### ISSUE TITLE
Automatic unpause / pause fails

### ISSUE THREAD

**Issue by tjerkkamstra** [andreashauschild/openttd-server#6]
Hi,

It seems that the automatic pause / unpause is broken in V13 when the console is opened in the OpenTTD server gui.
In the console it gives the following error:

`Command '@@@@_UnpauseCommand_1677323989205_@@@@' not found.`

Experienced this:
* The game does not autopause when all players are disconnected or spectating
* The game does not unpause after a manual savegame was made
*  When the player connects, it pauses the game but DOES actually unpause it again.
* When the console is not open, it works like it should.
* The game is however able to be unpaused manually in the console.

**Comment by andreashauschild** [comment]
Hi,

The behavior of the feature in the new version remains unchanged and is exactly as intended. If the console is opened, all auto features are disabled. In order for these features to work properly, the terminal must be set to English (the server should automatically set the terminal language to English).

- Server check if the terminal is open. If open all auto actions are skipped.
- Server checks if a player action was loggend in the terminal like:
  - has started a new company
  - has joined company
  - has left the game
  - closed connection
  - has joined spectators
- **If these logs occrued the server checks if it must be paused or unpaused.**
- The server checks every 30 seconds whether the game needs to be paused or unpaused, but only if no terminal is currently open.

Internally, all auto features involve reading and writing to the terminal. If the terminal is left open in the UI, it can become cluttered with unwanted information. For this reason, all auto actions are intentionally skipped when the terminal is open in the UI.

If the auto feature fails to work after the terminal has been closed for more than 3 minutes, this is considered a bug.

**Comment by tjerkkamstra** [comment]
Thanks for the quick info. This might be worth mentioning in the README.
I thought it was a bug due to the "Command '@@@@_UnpauseCommand_1677323989205_@@@@' not found." message in the console.

**Comment by tjerkkamstra** [comment]
Closed as not a bug but considered a feature.

**Comment by tjerkkamstra** [comment]
Closed as considered not a bug but a feature ;)

**Comment by andreashauschild** [comment]
The string: Command '@@@@UnpauseCommand_1677323989205@@@@' that u see is used to find the starting point of an issued pause command. The system searches for that and then the next lines to se if the command was executed.

By the way its documented directly in the UI ;)
![image](https://user-images.githubusercontent.com/25500623/221360937-231b90f5-3aa6-470a-9ee1-d6c43c28b2ff.png)

**Comment by tjerkkamstra** [comment]
Ah ok, I see. I'm not that familiar with the OpenTTD console (in fact I was not until today).

Thanks for pointing out. I'm an official idiot:P
